name: ShopGuiX
version: '0.0.2'
main: org.ibenrm01.shopGuiX.ShopGuiX
api-version: '1.21'
authors: [ Ibenrm01 ]
description: Shop GUI Plugin for EcoSyX
depend: [ EcoSyX ]
commands:
  shopgui:
    description: "Open shop / manage shop items"
    aliases: [ shop ]
  sellgui:
    description: "Sell items"
    aliases: [ sell ]
permissions:
  player.shop:
    description: "Browse and buy from the shop"
    default: true
  player.sell:
    description: "Sell items to the shop"
    default: true
  shop.op:
    description: "Add, remove, and edit shop items (admin)"
    default: op
